# Generated by Django 2.2.6 on 2019-10-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20191007_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Options',
        ),
    ]
