# Generated by Django 2.2.6 on 2019-10-07 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20191007_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='pud_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Churned'),
        ),
        migrations.AlterField(
            model_name='options',
            name='featured',
            field=models.BooleanField(default=0),
        ),
    ]
