# Generated by Django 2.2.6 on 2019-10-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_auto_20191007_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icecreams',
            new_name='Icecream',
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
