# Generated by Django 2.2.6 on 2019-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0005_auto_20191007_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='choices_text',
            field=models.CharField(max_length=200),
        ),
    ]
