# Generated by Django 2.2.6 on 2019-10-08 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0006_auto_20191008_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='ice_cream_text',
        ),
        migrations.AddField(
            model_name='icecream',
            name='available',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('FEATURED', 'Featured'), ('SEASONAL', 'Seasonal')], default='DAILY', max_length=255),
        ),
        migrations.AddField(
            model_name='icecream',
            name='date_churned',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Churned'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
