# Generated by Django 2.2.6 on 2019-10-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0007_auto_20191008_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='base',
            field=models.CharField(choices=[('CHOCOLATE', 'Chocolate'), ('VANILLA', 'Vanilla'), ('STRAWBERRY', 'Strawberry')], default='VANILLA', max_length=255),
        ),
        migrations.AddField(
            model_name='icecream',
            name='flavor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
