# Generated by Django 2.2.6 on 2019-10-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0008_auto_20191008_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='available',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('SEASONAL', 'Seasonal')], default='DAILY', max_length=255),
        ),
    ]
